const data=[{id:1,title:'Web Development Intern',company:'TechNova Solutions',location:'Ahmedabad / Remote',skills:['HTML','CSS','JavaScript'],duration:'3 Months'},{id:2,title:'Python Django Intern',company:'CodeCraft Labs',location:'Remote',skills:['Python','Django','SQL'],duration:'4 Months'},{id:3,title:'Frontend Developer Intern',company:'DigitalWorks',location:'Ahmedabad',skills:['HTML','CSS','JavaScript','Bootstrap'],duration:'3 Months'},{id:4,title:'Software Engineering Intern',company:'Innovate Systems',location:'Hybrid',skills:['Python','SQL','Git'],duration:'6 Months'}];
let profile=JSON.parse(localStorage.getItem('profile')||'null')||{name:'Student Demo',education:'B.Tech Computer Engineering',goal:'Web Development',skills:'HTML, CSS, JavaScript',interests:'Web Development, Software',projects:'Student Skill & Internship Finder'};let applications=JSON.parse(localStorage.getItem('applications')||'[]');let posted=JSON.parse(localStorage.getItem('posted')||'[]');let currentRole=localStorage.getItem('role')||'';
function showPage(id){if(!currentRole&&id!=='login'){id='login'}document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');if(id==='internships')render();if(id==='applications')renderApps();if(id==='company')renderCompany();scrollTo(0,0)}
function switchLogin(role){studentLogin.style.display=role==='student'?'block':'none';companyLogin.style.display=role==='company'?'block':'none';studentTab.classList.toggle('active',role==='student');companyTab.classList.toggle('active',role==='company')}
function login(role){currentRole=role;localStorage.setItem('role',role);studentNav.style.display=role==='student'?'inline-block':'none';companyNav.style.display=role==='company'?'inline-block':'none';showPage(role==='student'?'home':'company')}
function logout(){currentRole='';localStorage.removeItem('role');studentNav.style.display='none';companyNav.style.display='none';showPage('login')}
function skills(){return profile.skills.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean)}function allInternships(){return data.concat(posted)}function score(i){let s=skills();return Math.round(i.skills.filter(x=>s.includes(x.toLowerCase())).length/i.skills.length*100)}
function render(){let q=search.value.toLowerCase(),f=filter.value,arr=allInternships().filter(i=>(i.title+' '+i.company+' '+i.skills.join(' ')).toLowerCase().includes(q));if(f==='matched')arr=arr.filter(i=>score(i)>=50);list.innerHTML=arr.length?arr.map(i=>`<article class="internship-card"><h3>${i.title}</h3><p class="company">${i.company} • ${i.location}</p><p><b>Duration:</b> ${i.duration}</p><b>Required Skills:</b><div class="tags">${i.skills.map(s=>`<span class="tag">${s}</span>`).join('')}</div><span class="match ${score(i)<50?'low':''}">${score(i)}% Skill Match</span><br><button class="primary" onclick="apply(${i.id})">Apply Now</button> <button class="secondary" onclick="details(${i.id})">Details</button></article>`).join(''):'<div class="panel">No internships found.</div>'}
function details(id){let i=allInternships().find(x=>x.id===id);alert(`${i.title}\n\nCompany: ${i.company}\nRequired Skills: ${i.skills.join(', ')}\nDuration: ${i.duration}\nBasic Skill Match: ${score(i)}%`)}
function apply(id){if(currentRole!=='student'){alert('Please login as a student to apply.');return}let i=allInternships().find(x=>x.id===id);if(applications.some(a=>a.id===id)){alert('Already applied to this internship.');return}applications.push({id:i.id,title:i.title,company:i.company,status:'Applied'});localStorage.setItem('applications',JSON.stringify(applications));update();alert('Application submitted successfully!')}
function renderApps(){apps.innerHTML=applications.length?applications.map(a=>`<div class="application"><div><h3>${a.title}</h3><p>${a.company}</p></div><span class="status">${a.status}</span></div>`).join(''):'<div class="panel">No applications yet. Browse internships and apply.</div>'}
function saveProfile(){profile={name:name.value,education:education.value,goal:goal.value,skills:skillsInput.value,interests:interests.value,projects:projects.value};localStorage.setItem('profile',JSON.stringify(profile));saved.textContent='Profile saved!';update();setTimeout(()=>saved.textContent='',1800)}
function postInternship(){if(currentRole!=='company'){alert('Please login as a company.');return}let title=jobTitle.value.trim(),company=companyName.value.trim(),sk=jobSkills.value.split(',').map(x=>x.trim()).filter(Boolean);if(!title||!company||!sk.length){alert('Please enter title, company and required skills.');return}posted.push({id:Date.now(),title,company,skills:sk,duration:jobDuration.value,location:jobLocation.value});localStorage.setItem('posted',JSON.stringify(posted));jobTitle.value='';jobSkills.value='';renderCompany();alert('Internship posted successfully!')}
function renderCompany(){jobCount.textContent=allInternships().length;companyAppCount.textContent=applications.length;companyJobs.innerHTML=allInternships().map(i=>`<div class="job-row"><div><b>${i.title}</b><br><small>${i.company} • ${i.skills.join(', ')}</small></div><span>${i.duration}</span></div>`).join('')}
const skillsInput=document.getElementById('skills');function load(){name.value=profile.name;education.value=profile.education;goal.value=profile.goal;skillsInput.value=profile.skills;interests.value=profile.interests;projects.value=profile.projects;update();studentNav.style.display=currentRole==='student'?'inline-block':'none';companyNav.style.display=currentRole==='company'?'inline-block':'none';if(currentRole==='company')showPage('company');else if(currentRole==='student')showPage('home');else showPage('login')}function update(){skillCount.textContent=skills().length;appCount.textContent=applications.length}document.addEventListener('DOMContentLoaded',load);
